# 管理员登录session键名
SESSION_LOGIN = "SESSION_LOGIN"

# 用户头像地址
SESSION_HEAD_PORTRAIT = "SESSION_HEAD_PORTRAIT"

# 登录账号
SESSION_USER_ID = 'session_user_id'

# 用户是否为开发者
SESSION_IS_DEVELOPER = "SESSION_IS_DEVELOPER"

# 用户类型
SESSION_USER_TYPE = "SESSION_USER_TYPE"

# 登录重定向uri
SESSION_REDIRECT_URI = "SESSION_REDIRECT_URI"


# 登录次数(失败一次后需要输入验证码)
SESSION_LOGIN_TIME = "SESSION_LOGIN_TIME"

# 验证码
SESSION_LOGIN_VALIDATE = "SESSION_LOGIN_VALIDATE"

# 第三方登录标志（包括设备管理系统厂商帐号）
SESSION_LOGIN_THIRD = "SESSION_LOGIN_THIRD"

# 注册成功标志
SESSION_REGISTER_SUCCESS = "SESSION_REGISTER_SUCCESS"

#################################################################
# 记住登录账户的cookie key
COOKIE_USER_ACCOUNT = "COOKIE_USER_ACCOUNT"

